# Site settings
title: Yeiner Fernández
email: yeinerfblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love Sotfware Development, who doesn't?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yeinerf.com" # the base hostname & protocol for your site
twitter_username: yeinerf
github_username:  yefb
comments: true

# Build settings
markdown: kramdown
